/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: [
      "static.coupangcdn.com",
      "pages.coupang.com",
      "image1.coupangcdn.com",
      "image2.coupangcdn.com",
      "image3.coupangcdn.com",
      "image4.coupangcdn.com",
      "image5.coupangcdn.com",
      "image6.coupangcdn.com",
      "image7.coupangcdn.com",
      "image9.coupangcdn.com",
      "image10.coupangcdn.com",
      "image11.coupangcdn.com",
      "image12.coupangcdn.com",
      "image13.coupangcdn.com",
      "image14.coupangcdn.com",
      "thumbnail1.coupangcdn.com",
      "thumbnail2.coupangcdn.com",
      "thumbnail3.coupangcdn.com",
      "thumbnail4.coupangcdn.com",
      "thumbnail5.coupangcdn.com",
      "thumbnail6.coupangcdn.com",
      "thumbnail7.coupangcdn.com",
      "thumbnail8.coupangcdn.com",
      "thumbnail9.coupangcdn.com",
      "thumbnail10.coupangcdn.com",
      "thumbnail11.coupangcdn.com",
      "thumbnail12.coupangcdn.com",
      "thumbnail13.coupangcdn.com",
      "thumbnail14.coupangcdn.com",
      "i.ytimg.com",
      "recipe1.ezmember.co.kr",
    ],
  },
};

export default nextConfig;
